export type FieldType = 'text' | 'textarea' | 'number' | 'boolean' | 'json' | 'date' | 'select';

export type Field = {
  name: string;
  label: string;
  type: FieldType;
  required?: boolean;
  options?: { value: string; label: string }[];
  hint?: string;
  /** text primary keys the admin must type on create (no DB default). */
  pkInput?: boolean;
};

export type Resource = {
  key: string;
  table: string;
  label: string;
  singular: string;
  description: string;
  group: string;
  icon: string;
  productScoped: boolean;
  /** true when the PK is a uuid with a DB default (hidden on create). */
  pkAutoGenerated: boolean;
  defaultSort?: { column: string; ascending: boolean };
  fields: Field[];
  listColumns: string[];
};

export const RESOURCES: Resource[] = [
  // ---- Content ----
  {
    key: 'containers',
    table: 'containers',
    label: 'Content Containers',
    singular: 'Container',
    description: 'Logical groupings the app uses to organise comics, jokes and other content.',
    group: 'Content',
    icon: 'boxes',
    productScoped: false,
    pkAutoGenerated: false,
    defaultSort: { column: 'sort_order', ascending: true },
    fields: [
      { name: 'id', label: 'ID (slug)', type: 'text', required: true, pkInput: true, hint: 'Stable text identifier referenced by content rows.' },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'content_type', label: 'Content type', type: 'text', hint: 'e.g. comics, jokes' },
      { name: 'sort_order', label: 'Sort order', type: 'number' },
      { name: 'is_visible', label: 'Visible', type: 'boolean' },
    ],
    listColumns: ['id', 'name', 'content_type', 'sort_order', 'is_visible'],
  },
  {
    key: 'comics',
    table: 'comics',
    label: 'Comics',
    singular: 'Comic',
    description: 'Full comic issues shown in the app catalogue.',
    group: 'Content',
    icon: 'book-open',
    productScoped: false,
    pkAutoGenerated: true,
    defaultSort: { column: 'issue_number', ascending: true },
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'issue_number', label: 'Issue number', type: 'number' },
      { name: 'year', label: 'Year', type: 'number' },
      { name: 'cover_image_url', label: 'Cover image URL', type: 'text' },
      { name: 'thumbnail_url', label: 'Thumbnail URL', type: 'text' },
      { name: 'pdf_url', label: 'PDF URL', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'container_id', label: 'Container ID', type: 'text' },
      { name: 'cms_id', label: 'CMS ID', type: 'text' },
      { name: 'is_premium', label: 'Premium', type: 'boolean' },
    ],
    listColumns: ['issue_number', 'title', 'year', 'is_premium'],
  },
  {
    key: 'comic-strips',
    table: 'comic_strips',
    label: 'Comic Strips',
    singular: 'Strip',
    description: 'Daily / short strips composed of ordered panels.',
    group: 'Content',
    icon: 'gallery-horizontal',
    productScoped: false,
    pkAutoGenerated: true,
    defaultSort: { column: 'published_date', ascending: false },
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'published_date', label: 'Published date', type: 'date' },
      { name: 'panels', label: 'Panels', type: 'json', hint: 'JSON array of panel objects.' },
      { name: 'preview_aspect_ratio', label: 'Preview aspect ratio', type: 'number' },
      { name: 'pdf_url', label: 'PDF URL', type: 'text' },
      { name: 'cms_id', label: 'CMS ID', type: 'text' },
      { name: 'is_free', label: 'Free', type: 'boolean' },
    ],
    listColumns: ['title', 'published_date', 'is_free'],
  },
  {
    key: 'jokes',
    table: 'jokes',
    label: 'Jokes',
    singular: 'Joke',
    description: 'Joke pages and editions.',
    group: 'Content',
    icon: 'smile',
    productScoped: false,
    pkAutoGenerated: true,
    defaultSort: { column: 'edition_number', ascending: false },
    fields: [
      { name: 'text_content', label: 'Text', type: 'textarea' },
      { name: 'image_url', label: 'Image URL', type: 'text' },
      { name: 'thumbnail_url', label: 'Thumbnail URL', type: 'text' },
      { name: 'pdf_url', label: 'PDF URL', type: 'text' },
      { name: 'edition_number', label: 'Edition number', type: 'number' },
      { name: 'container_id', label: 'Container ID', type: 'text' },
      { name: 'cms_id', label: 'CMS ID', type: 'text' },
      { name: 'is_free', label: 'Free', type: 'boolean' },
    ],
    listColumns: ['edition_number', 'text_content', 'is_free'],
  },
  {
    key: 'characters',
    table: 'characters',
    label: 'Characters',
    singular: 'Character',
    description: 'Character profiles displayed in the app.',
    group: 'Content',
    icon: 'users',
    productScoped: false,
    pkAutoGenerated: true,
    defaultSort: { column: 'sort_order', ascending: true },
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'bio', label: 'Bio', type: 'textarea' },
      { name: 'avatar_image_url', label: 'Avatar image URL', type: 'text' },
      { name: 'sort_order', label: 'Sort order', type: 'number' },
    ],
    listColumns: ['sort_order', 'name', 'description'],
  },
  {
    key: 'collection-categories',
    table: 'collection_categories',
    label: 'Collection Categories',
    singular: 'Category',
    description: 'Home collection tiles that route into content sections.',
    group: 'Content',
    icon: 'layout-grid',
    productScoped: false,
    pkAutoGenerated: false,
    defaultSort: { column: 'sort_order', ascending: true },
    fields: [
      { name: 'id', label: 'ID (slug)', type: 'text', required: true, pkInput: true },
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'subtitle', label: 'Subtitle', type: 'text' },
      { name: 'background_color', label: 'Background color', type: 'text', hint: 'Hex or token, e.g. #E63329' },
      { name: 'character_asset', label: 'Character asset', type: 'text' },
      { name: 'cms_id', label: 'CMS ID', type: 'text', hint: 'Catalog CMS id. Used as the detail route param and the comics container_id.' },
      { name: 'action_route', label: 'Action route', type: 'text' },
      { name: 'sort_order', label: 'Sort order', type: 'number' },
      { name: 'is_visible', label: 'Visible', type: 'boolean' },
    ],
    listColumns: ['sort_order', 'id', 'title', 'cms_id', 'is_visible'],
  },
  {
    key: 'games',
    table: 'games',
    label: 'Games',
    singular: 'Game',
    description: 'Embedded games surfaced in the app.',
    group: 'Content',
    icon: 'gamepad-2',
    productScoped: false,
    pkAutoGenerated: true,
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'cover_image_url', label: 'Cover image URL', type: 'text' },
      { name: 'game_url', label: 'Game URL', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
    ],
    listColumns: ['title', 'game_url'],
  },

  // ---- Localization ----
  {
    key: 'translations',
    table: 'product_translations',
    label: 'Translations',
    singular: 'Translation',
    description: 'Localised strings keyed by language, namespace and key.',
    group: 'Localization',
    icon: 'languages',
    productScoped: true,
    pkAutoGenerated: true,
    defaultSort: { column: 'key', ascending: true },
    fields: [
      { name: 'language_code', label: 'Language code', type: 'text', required: true, hint: 'e.g. es, en' },
      { name: 'namespace', label: 'Namespace', type: 'text', required: true },
      { name: 'key', label: 'Key', type: 'text', required: true },
      { name: 'value', label: 'Value', type: 'textarea', required: true },
    ],
    listColumns: ['language_code', 'namespace', 'key', 'value'],
  },
  {
    key: 'languages',
    table: 'product_languages',
    label: 'Languages',
    singular: 'Language',
    description: 'Languages available for this product.',
    group: 'Localization',
    icon: 'globe',
    productScoped: true,
    pkAutoGenerated: true,
    fields: [
      { name: 'code', label: 'Code', type: 'text', required: true },
      { name: 'display_name', label: 'Display name', type: 'text', required: true },
      { name: 'is_default', label: 'Default', type: 'boolean' },
    ],
    listColumns: ['code', 'display_name', 'is_default'],
  },

  // ---- Configuration ----
  {
    key: 'config',
    table: 'product_config',
    label: 'Config Values',
    singular: 'Config value',
    description: 'Key/value configuration read by the app at runtime.',
    group: 'Configuration',
    icon: 'settings',
    productScoped: true,
    pkAutoGenerated: true,
    defaultSort: { column: 'key', ascending: true },
    fields: [
      { name: 'key', label: 'Key', type: 'text', required: true },
      { name: 'value', label: 'Value', type: 'textarea', required: true },
    ],
    listColumns: ['key', 'value'],
  },
  {
    key: 'feature-flags',
    table: 'product_feature_flags',
    label: 'Feature Flags',
    singular: 'Feature flag',
    description: 'Toggle app features without a release.',
    group: 'Configuration',
    icon: 'flag',
    productScoped: true,
    pkAutoGenerated: true,
    defaultSort: { column: 'key', ascending: true },
    fields: [
      { name: 'key', label: 'Key', type: 'text', required: true },
      { name: 'enabled', label: 'Enabled', type: 'boolean' },
    ],
    listColumns: ['key', 'enabled'],
  },
  {
    key: 'assets',
    table: 'product_assets',
    label: 'Assets',
    singular: 'Asset',
    description: 'Branded media (logos, icons, images) referenced by key.',
    group: 'Configuration',
    icon: 'image',
    productScoped: true,
    pkAutoGenerated: true,
    defaultSort: { column: 'key', ascending: true },
    fields: [
      { name: 'key', label: 'Key', type: 'text', required: true },
      { name: 'url', label: 'URL', type: 'text', required: true },
      { name: 'mime_type', label: 'MIME type', type: 'text' },
      { name: 'metadata', label: 'Metadata', type: 'json' },
    ],
    listColumns: ['key', 'url', 'mime_type'],
  },
  {
    key: 'branding',
    table: 'product_branding',
    label: 'Branding',
    singular: 'Branding',
    description: 'Design tokens (colors, fonts, spacing) that theme the app.',
    group: 'Configuration',
    icon: 'palette',
    productScoped: true,
    pkAutoGenerated: true,
    fields: [
      { name: 'colors', label: 'Colors', type: 'json' },
      { name: 'gradients', label: 'Gradients', type: 'json' },
      { name: 'fonts', label: 'Fonts', type: 'json' },
      { name: 'font_sizes', label: 'Font sizes', type: 'json' },
      { name: 'font_weights', label: 'Font weights', type: 'json' },
      { name: 'radius', label: 'Radius', type: 'json' },
      { name: 'spacing', label: 'Spacing', type: 'json' },
      { name: 'shadows', label: 'Shadows', type: 'json' },
    ],
    listColumns: ['id'],
  },

  // ---- Navigation ----
  {
    key: 'menu-items',
    table: 'product_menu_items',
    label: 'Menu Items',
    singular: 'Menu item',
    description: 'Primary navigation entries.',
    group: 'Navigation',
    icon: 'menu',
    productScoped: true,
    pkAutoGenerated: true,
    defaultSort: { column: 'position', ascending: true },
    fields: [
      { name: 'key', label: 'Key', type: 'text', required: true },
      { name: 'label', label: 'Label', type: 'text' },
      { name: 'label_i18n_key', label: 'Label i18n key', type: 'text' },
      { name: 'route', label: 'Route', type: 'text' },
      { name: 'external_url', label: 'External URL', type: 'text' },
      { name: 'icon', label: 'Icon', type: 'text' },
      { name: 'icon_url', label: 'Icon URL', type: 'text' },
      { name: 'position', label: 'Position', type: 'number' },
      { name: 'parent_key', label: 'Parent key', type: 'text' },
      { name: 'feature_flag', label: 'Feature flag', type: 'text' },
      { name: 'min_app_version', label: 'Min app version', type: 'text' },
      { name: 'max_app_version', label: 'Max app version', type: 'text' },
      { name: 'badge_text', label: 'Badge text', type: 'text' },
      { name: 'badge_color', label: 'Badge color', type: 'text' },
      { name: 'auth_required', label: 'Auth required', type: 'boolean' },
      { name: 'visible', label: 'Visible', type: 'boolean' },
    ],
    listColumns: ['position', 'key', 'label', 'route', 'visible'],
  },
  {
    key: 'footer-items',
    table: 'product_footer_items',
    label: 'Footer Items',
    singular: 'Footer item',
    description: 'Footer links and their grouping.',
    group: 'Navigation',
    icon: 'panel-bottom',
    productScoped: true,
    pkAutoGenerated: true,
    defaultSort: { column: 'position', ascending: true },
    fields: [
      { name: 'key', label: 'Key', type: 'text', required: true },
      { name: 'label', label: 'Label', type: 'text' },
      { name: 'url', label: 'URL', type: 'text' },
      { name: 'icon', label: 'Icon', type: 'text' },
      { name: 'group', label: 'Group', type: 'text' },
      { name: 'position', label: 'Position', type: 'number' },
    ],
    listColumns: ['position', 'key', 'label', 'group'],
  },
];

export const RESOURCE_GROUPS = ['Content', 'Localization', 'Configuration', 'Navigation'];

// Content management (comics, jokes, characters, containers, collection
// categories, games, strips) is intentionally hidden from the UI for now; the
// tables and their RLS policies remain in place. To re-enable it later, remove
// 'Content' from HIDDEN_GROUPS.
export const HIDDEN_GROUPS = ['Content'];

export const VISIBLE_GROUPS = RESOURCE_GROUPS.filter((g) => !HIDDEN_GROUPS.includes(g));

export const VISIBLE_RESOURCES = RESOURCES.filter((r) => !HIDDEN_GROUPS.includes(r.group));

export function resourceByKey(key: string): Resource | undefined {
  return RESOURCES.find((r) => r.key === key);
}

export function isResourceVisible(key: string): boolean {
  const r = resourceByKey(key);
  return !!r && !HIDDEN_GROUPS.includes(r.group);
}
